// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qowktsaxfmcdlusddbzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvd2t0c2F4Zm1jZGx1c2RkYnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjkzOTIsImV4cCI6MjA2NjQwNTM5Mn0.dst56ZyxSLtYfMPR8jAqHYZE3BfUGpdL-pTtmu4QQZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);